[[rewriting-history]]
Rewriting History
-----------------

Modifying existing commits and recovering from history rewrites. Advises
on when history rewriting is useful, basic methods of rewriting history
and how to avoid losing data when doing so.

[[when-is-it-useful-to-rewrite-history]]
When is it useful to rewrite history?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[list-all-changes-including-history-rewrites]]
List all changes including history rewrites
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[list-all-changes-including-history-rewrites-with-diffs]]
List all changes including history rewrites with diffs
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[remove-all-current-changes-to-files]]
Remove all current changes to files
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[reset-a-branch-to-a-previous-commit]]
Reset a branch to a previous commit
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[reset-a-branch-to-the-upstream-version]]
Reset a branch to the upstream version
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[rebase-commits-on-top-of-another-branch]]
Rebase commits on top of another branch
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[rebase-commits-interactively]]
Rebase commits interactively
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[pull-a-branch-and-rebase-commits]]
Pull a branch and rebase commits
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[rewriting-the-entire-history-of-a-repository]]
Rewriting the entire history of a repository
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

How and why to recreate the entire global history of a Git repository.
Walk through a few advanced use-cases such as sanitizing before a public
release, changing internal to external email addresses and creating a
new repository from a subsection of another.

